---

ibm_cloud_api_key:
ic_api_key: "{{ ibm_cloud_api_key }}"
rh_ocp_cluster_mgr_offline_token:
oc_installer_work_directory: '$PWD/rhocp_prep'
ocp_installer_init_directory: '$PWD/rhocp_init'
ocp_cluster_hosts_private_key: '/root/.ssh/hosts_rsa'
ocp_resource_prefix: 'ocp-test'
ibmcloud_target_rg: 'default'
ocp_directories:
  - '$ocp_installer_work_directory/cli_tar'
  - '$ocp_installer_work_directory/cli_extracted'
  - '$ocp_installer_work_directory/installer_tar'
  - '$ocp_installer_work_directory/installer_extracted'
  - '$ocp_installer_work_directory/ccoctl_credentials_requests'
  - '$ocp_installer_init_directory'
# defaults file for aap_setup_download

# Acquire your token at https://access.redhat.com/management/api/
# see https://access.redhat.com/articles/3626371
#
# aap_setup_down_offline_token:

ocp_client_cli: 'https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz'
ocp_setup_down_release: 'https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz'
ocp_setup_down_token_url: 'https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token'
ocp_setup_down_images_url: 'https://api.access.redhat.com/management/v1/images/cset/{{ aap_setup_down_release }}'

# which version of the installer to download
#aap_setup_down_version: "2.5"

# Which minor version to download, eg {{ aap_setup_down_version }}-12
#aap_setup_down_version_patch: false  # set to false to download the latest version, 12 for 2.5-12

# Which system architecture to download for
#aap_setup_arch: x86_64

# Which RHEL version are you using (8 or 9)
#aap_setup_rhel_version: "{{ ansible_distribution_major_version | default(8, true) }}"

# where to download the setup installer file
#aap_setup_down_dest_dir: "{{ aap_setup_working_dir | default('/var/tmp') }}"

# do you download the "setup-bundle" or only the (online) "setup"?
#aap_setup_down_type: setup-bundle

# Download containerized installer
#aap_setup_containerized: false
...
